config/routes.rb
Rails.application.routes.draw do

  apipie
  namespace :api, defaults: { format: 'json' } do
    resources :children, only: [:create, :index] do
      resources :reservations

      member do
        get     'curated'
        get     'development_elements'
        get     'save_availability'
        patch   'update_availability'
      end

      resources :availability, only: [:create, :update]
    end
    resources :subscriptions, only: [:index]
    resources :schedules, only: [:index, :update]
    resources :users, only: [:update]

    post    'register',           to: 'registrations#create'
    post    'facebook_callback',  to: 'registrations#facebook'
    post    'login',              to: 'sessions#create'
    post    'facebook_callback',  to: 'sessions#facebook'
    post    'forgot_password',    to: 'sessions#forgot'
    delete  'logout',             to: 'sessions#destroy'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :contact_requests
  resources :zipcodes do
    collection do
      post :contact_request
    end
  end

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :static_page_contents
  resources :promo_codes
  get 'cards/new'

  root 'static_pages#index'

  get 'comming_soon', to: 'static_pages#comming_soon', as: 'comming_soon'
  get 'faq',      to: 'static_pages#faq'
  get 'terms',    to: 'static_pages#terms'
  get 'privacy',  to: 'static_pages#privacy'
  get 'become-partner', to: 'static_pages#partners', as: 'partner_signup'
  post 'become-partner', to: 'static_pages#partners'

  post 'charged_successfully', to: 'subscriptions#charged_successfully'

  get 'onboard', to: 'users#onboard', as: 'onboard'

  resources :schedules, only: [:index, :show] do
    patch 'archive',   on: :member
    patch 'unarchive', on: :member

    collection do
      get  'curated'
    end

    resources :reservations, only: [:new, :create, :destroy]
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                                                                          registrations: 'users/registrations',
                                                                                          passwords: 'users/passwords' }

  resources :users, only: [:show] do
    collection do
      get   :select_plan
      get   :new_referal_code
      post  :check_referal_code
    end

    member do
      patch 'add_child'
    end
    post :promo_code
    resources :children, except: [:index, :show]
  end

  resources :children, only: [:show] do
    ## subscriptions ##
    resources :subscriptions, only: [:new, :create, :show, :destroy]

    collection do
      get   'achievements'
    end
    member do
      get  'curated'
    end
  end

  resources :partners do
    collection do
      get :loadmore
    end
    resources :klasses, :schedules, except: [:index, :show]
  end

  # match 'users/:id' => 'users#destroy', via: :delete, as: 'admin_destroy_user'

  resources :cities, path: 'city', except: [:index, :show]
  resources :activities, except: [:index, :show]

  resources :rewards, only: [:index] do
    member do
      get   'claim'
    end
  end

  # Admin's Devise settings
  # devise_for :admins, path: 'admin', path_names: { sign_in: 'login', sign_out: 'logout' }

  ## cards ##
  resources :cards
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    if params[:mobileview].present?
      cookies[:mobile] = true
    end
    @featured_partners = Partner.all.featured_partners
    if user_signed_in?
      redirect_to current_user
    end
  end

  def faq
    @faqs = FaqGroup.all
  end

  def terms
  end

  def privacy
  end

  def partners
    @partnership = PartnershipSignUp.new

    if request.post?
      @partnership = PartnershipSignUp.new(partner_params)

      if @partnership.save
        NotificationMailer.notify(@partnership).deliver_now
        redirect_to partner_signup_path, notice: 'Thank you, we will contact you soon!'
      else
        redirect_to partner_signup_path, notice: 'Something went wrong'
      end
    end
  end

  # def invite
  # end

  # def pricing
  # end

  def partner_params
    params.require(:partnership_sign_up).permit(:city, :company_name, :website, :name, :email, :phone, :address, :comments)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/comming_soon.html.haml
- provide(:title, "Unlimited Classes For Your Children")
.content.home-page.white-bg.no-padding
  / Section - Main
  #section-main.section-row
    .container
      .row
        .col-md-6
          %h2.page-heading.section-headline One Pass
          %br
            %h2.page-heading.section-headline Unlimited Activities
            .text-center
              %h3.page-heading.section-subheading For Children
      .row
        .col-md-12
          .col-md-6
            %p.section-text 
              %h3 WE ARE GETTING THERE!
              Unfortunetly GeniusPass isn't in your neighbourhood just yet. 
              %br/
              Stay tuned!
          .col-md-6
            .map-image
              = image_tag "malaysia-map.png", title: "Malaysia", alt: "Malaysia"
              %p.map-label We're Now In Malaysia
        .col-md-12
          = form_tag contact_request_zipcodes_path do
            .col-md-6
              = text_field_tag :email, nil,  placeholder: "Email", class: 'contact-request-text'
            .col-md-3
              = text_field_tag :zipcode, nil, placeholder: 'Pincode', class: 'contact-request-text'
            .col-md-3
              = submit_tag "Get moving", class: 'btn btn-primary'
  / Section - Flags
  #section-flags.section-row
    .container
      .row
        .col-md-5.text-left-not-xs.text-left-not-sm.text-center-xs.text-center-sm
          %span.small-heading Expanding Across
          %h3.page-heading.heading
            8 Cities
            %span Counting
        .col-md-7
          .flag-list
            %ul
              %li.flag-icon= image_tag "flags/SG.png", alt: "Singapore", title: "Singapore"
              %li.flag-icon= image_tag "flags/MY.png", alt: "Malaysia", title: "Malaysia"
              %li.flag-icon= image_tag "flags/KR.png", alt: "South Korea", title: "South Korea"
              %li.flag-icon= image_tag "flags/IN.png", alt: "India", title: "India"
              %li.flag-icon= image_tag "flags/ID.png", alt: "Indonesia", title: "Indonesia"
              %li.flag-icon= image_tag "flags/HK.png", alt: "Hong Kong", title: "Hong Kong"
              %li.flag-icon= image_tag "flags/CN.png", alt: "China", title: "China"
              %li.flag-icon= image_tag "flags/AU.png", alt: "Australia", title: "Australia"
  / Section - Features
  #section-features.section-row
    .container
      .slider-features.row
        .slider-features-container.col-sm-6.col-md-4.col-md-offset-1
          .slider-phone-frame
          .slider-features-images
            .feature-image= image_tag "web-app-screenshot1.png", alt: "App Screenshot", title: "App Screenshot"
            .feature-image= image_tag "web-app-screenshot2.png", alt: "App Screenshot", title: "App Screenshot"
            .feature-image= image_tag "web-app-screenshot3.png", alt: "App Screenshot", title: "App Screenshot"
            .feature-image= image_tag "web-app-screenshot4.png", alt: "App Screenshot", title: "App Screenshot"
        .slider-features-container.col-sm-6.col-md-6.text-center-xs
          .slider-features-content
            .feature-content
              %h1.page-heading.feature-title
                Choose
                %span Activity
              %p.feature-description Variety of activities for your children
            .feature-content
              %h1.page-heading.feature-title
                Choose
                %span Location
              %p.feature-description Search preferred locations near you
            .feature-content
              %h1.page-heading.feature-title
                %span Reserve
                Activities
              %p.feature-description Walk-in to explore, enjoy and learn
            .feature-content
              %h1.page-heading.feature-title
                %span IOS and Android
                Mobile App
              %p.feature-description Launching soon
          .slider-nav
            .slider-dots
            .slider-arrows
  / Section - Subscription
  /#section-subscription.section-row
  /  .container
  /    %p.section-text.text-center Keep up-to-date with our latest happenings!
  /    .mc_embed_signup.subscription-form-container
  /      %form#mc-embedded-subscribe-form.validate.subscription-form{:action => "//geniuspass.us10.list-manage.com/subscribe/post?u=06b2675db3a573a09ca434ca3&id=2b51fe0248", :method => "post", :name => "mc-embedded-subscribe-form", :target => "_blank"}
  /        .mc-field-group
  /          %input#mce-EMAIL.form-field{:name => "EMAIL", :placeholder => "Enter your email...", :type => "email"}/
  /          / real people should not fill this in and expect good things - do not remove this or risk form bot signups
  /          %div{:style => "position: absolute; left: -5000px;"}
  /            %input{:name => "b_06b2675db3a573a09ca434ca3_2b51fe0248", :tabindex => "-1", :type => "text", :value => ""}
  /          %input#mc-embedded-subscribe.form-submit-btn{:name => "submit", :type => "submit", :value => "Submit"}/
  /        #mce-responses.clear
  /          #mce-error-response.response{:style => "display:none"}
  /          #mce-success-response.response{:style => "display:none"}


  / Section - Partners
  #section-partners.section-row
    .container
      %h1.page-heading.section-heading Our Partners
      .partners-list
        .row
          - ary = [3, 5, 4, 5, 4, 3]
          - i = 0
          - @featured_partners = Partner.all.featured_partners.includes( :activities )
          - @featured_partners.map do |partner|
            .col-sm-4{ :class => "col-md-#{ary[i]}"}
              - i = i+1
              .partner-details
                .partner-info
                  = image_tag partner.img_url, :class => "partner-bg"
                  - if partner.logo.present?
                    = image_tag partner.logo.thumb.url, :class => "partner-logo"
                  - else
                    = image_tag "logo.png", alt: "Company Name - 1", title: "Company Name - 1", class: "partner-logo default-partner-logo"
                  .label-title= partner.company
                  .bg-overlay
                - if partner.activities.present?
                  .label-activities= partner.try(:activities).try(:pluck, :name).uniq.try(:join ,", ")

          .col-sm-4{ :class => "col-md-3"}
            .partner-details{style: 'background: orange'}
              .partner-info
                %br/
                %br/
                %br/
                %h2.text-center= "#{Partner.count} partners available"
                %br/
                .label-title= link_to "View more..", partners_path

  / Section - Location
  #section-location.section-row
    %div{:style => "width: 100%;"}
      #map.map-height-main{:style => "width: 100%"}
    = render :partial => "shared/map",
            :locals => { :markers => markers_ary( Partner.all)}

    = link_to partners_path, :class => "location-info hidden-xs" do
      .location-info-container
        %h3.page-heading.location-info-counter= Partner.count
        %h4.page-heading.location-info-title Activities Location
        %span.location-info-description Find nearby places
      .location-info-bar See All +

app/views/static_pages/faq.html.erb
<% provide(:title, "Frequently Asked Questions") %>
<% provide(:page_title_bg, asset_path('background-footer.jpg')) %>
<div class="content faq-page white-bg">
  <%= render partial: 'layouts/page_title', locals: { page_title: 'FAQ' } %>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <% if @faqs.present? %>
          <h1>Faqs</h1>
          <hr>
          <ul id='faq-sidebar'>
            <% @faqs.each do |faq| %>
              <%= link_to "##{faq.name.parameterize}" do %>
                <li>
                  <i class="fa fa-dot-circle-o" aria-hidden="true"></i>
                    <%= faq.name %>
                  <i class='fa fa-chevron-right pull-right'></i>
                </li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
      </div>

      <div class="col-md-9">
        <% if @faqs.present? %>
          <% @faqs.each do |faq| %>
            <div id="<%= faq.name.parameterize %>">
              <h1><%= faq.name %></h1>
              <hr>
              <%= faq.content.html_safe %>
            </div>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<% provide(:title, "Unlimited Classes For Your Children") %>

<% content_for :bottom_js do %>
  <%= javascript_include_tag 'slick.min' %>
  <%= javascript_include_tag 'chosen.min' %>
  <%= javascript_include_tag 'ion.rangeSlider.min' %>
  <%= javascript_include_tag 'moment.min' %>
  <%= javascript_include_tag 'frontpage' %>
<% end %>

<div class="content home-page white-bg no-padding">
  <%= render 'shared/notice', locals: { flash: flash } if flash.present? %>

  <!-- / Section - Main -->
  <div class="section-row <%= 'mobile-main' if cookies[:mobile].present? %>" id="section-main">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
        </div>
        <div class="col-md-6 <%= 'mobile' if cookies[:mobile].present? %> header-text-container">
          <h1>Discover The Best Activities Combination For Your Children</h1>
          <p class="lead">WE CURATE, YOU DECIDE!</p>
        </div>

        <div class="col-md-6">
          <%= form_tag contact_request_zipcodes_path, class: 'form-inline send-request-zipcode-form', id: 'top-request-zipcode-form' do %>
            <div class="form-group">
              <div class="user-email">
                <%= email_field_tag :email, nil,  placeholder: "Email", class: 'contact-request-text', required: true %>
              </div>
            </div>

            <div class="form-group">
              <div class="user-postcode">
                <%= text_field_tag :zipcode, nil, placeholder: 'Postcode', class: 'contact-request-text', required: true %>
              </div>
            </div>

            <%= submit_tag "Get Started", class: 'get-started-btn btn btn-primary' %>
          <% end %>
        </div>

        <% if cookies[:mobile].blank? %>
        <div class="col-md-6 right-header-activities">
          <div class="header-activities">
            <%= image_tag 'dance.png' %>
            <div class="title">DANCES</div>
          </div>
          <div class="header-activities">
            <%= image_tag 'art.png' %>
            <div class="title">ARTS</div>
          </div>
          <div class="header-activities">
            <%= image_tag 'sports.png' %>
            <div class="title">SPORTS</div>
          </div>
          <div class="header-activities">
            <%= image_tag 'fitness.png' %>
            <div class="title">FITNESS</div>
          </div>
          <div class="header-activities">
            <%= image_tag 'martial.png' %>
            <div class="title">MARTIAL</div>
          </div>
          <div class="header-activities">
            <%= image_tag 'education.png' %>
            <div class="title">EDUCATION</div>
          </div>
          <div class="header-activities">
            <%= image_tag 'music.png' %>
            <div class="title">MUSIC</div>
          </div>
        </div>
        <% end %>


      </div>

    </div>
  </div>

  <% if cookies[:mobile].blank? %>
  <div class="section-row cta-container">
    <div class="container">
      <div class="row">
        <div class="col-md-9 lead-text">
          <h2>Sign Up For Free & Get 2 FREE Activities Worth RM50 For Your Child</h2>
        </div>
        <div class="col-md-3 lead-btn">
          <%= link_to 'Get Started', '#', class: 'btn btn-primary btn-block', id: 'top-get-started-btn' %>
        </div>
      </div>
    </div>
  </div>

  <!-- / Section - Features -->
  <div class="section-row why-geniuspass-container gray-bg mid">
    <div class="container">
      <div class="row">
        <h2>Why GeniusPass?</h2>
        <p class='headline-description'>These Are Why Your Children Will Excel With Us</p>

        <div class="col-md-6">
          <div class="col-md-6 benefits-container">
            <%= image_tag 'personalize-curated-activities.png' %>
            <div class="title">Personalize Curated Activities</div>
          </div>
          <div class="col-md-6 benefits-container">
            <%= image_tag 'all-rounded-child-development.png' %>
            <div class="title">All-Rounded Child Development</div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="col-md-6 benefits-container">
            <%= image_tag 'variety-development-activities.png' %>
            <div class="title">Variety Of Development Activities</div>
          </div>
          <div class="col-md-6 benefits-container">
            <%= image_tag 'expert-research.png' %>
            <div class="title">Expert Research</div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="col-md-6 benefits-container">
            <%= image_tag 'track-child-progress.png' %>
            <div class="title">Track Child Progress Effectively</div>
          </div>
          <div class="col-md-6 benefits-container">
            <%= image_tag 'affordable-save-money.png' %>
            <div class="title">Affordable & Save Money </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="col-md-6 benefits-container">
            <%= image_tag 'time-flexibility.png' %>
            <div class="title">Time Flexibility</div>
          </div>
          <div class="col-md-6 benefits-container">
            <%= image_tag 'convenient.png' %>
            <div class="title">Convenient To Your Location</div>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="section-row mid elements-container">
    <div class="container">
      <div class="row">
        <h2>GeniusPass Develops 7 Brain’s Components</h2>
        <p class='headline-description'>We Focus On Developing All-Rounded Capable Children</p>

        <div class="col-md-12">
          <div class="components-div">
            <div class="component">
              <%= image_tag 'analytical.png' %>
              <div class='title'>ANALYTICAL</div>
            </div>

            <div class="component">
              <%= image_tag 'intellectual.png' %>
              <div class='title'>INTELLECTUAL</div>
            </div>

            <div class="component">
              <%= image_tag 'logical.png' %>
              <div class='title'>LOGICAL</div>
            </div>

            <div class="component">
              <%= image_tag 'physical.png' %>
              <div class='title'>PHYSICAL</div>
            </div>

            <div class="component">
              <%= image_tag 'creativity.png' %>
              <div class='title'>CREATIVITY</div>
            </div>

            <div class="component">
              <%= image_tag 'artistic.png' %>
              <div class='title'>ARTISTIC</div>
            </div>

            <div class="component">
              <%= image_tag 'memory.png' %>
              <div class='title'>MEMORY</div>
            </div>

          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="section-row steps-container gray-bg mid">
    <div class="container">
      <div class="row">
        <h2>Transform Your Children with 3 Steps</h2>
        <p class='headline-description'></p>
        <div class="col-md-4">
          <div class="brief-title-div">
            <%= image_tag 'step-1-note.png' %>
            <div class="description">
              <p>Discover whether your child is left or right-brain oriented.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="brief-title-div">
            <%= image_tag 'step-2-love.png' %>
            <div class="description">
              <p>Send your child to recommended curated activities in top centres.</p>
            </div>
          </div>

        </div>
        <div class="col-md-4">
          <div class="brief-title-div">
            <%= image_tag 'step-3-graph.png' %>
            <div class="description">
              <p>Boost up your child’s development with our fun tracking system!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="section-row mobile-app-container mid">
    <div class="container">
      <div class="row">
        <div class="col-md-5 left-container">
          <%= image_tag 'mobile-app.png' %>
        </div>

        <div class="col-md-7 right-container">
          <h2>Launching Soon!</h2>

          <p>GeniusPass mobile application enables seamless experience with an easy-to-use booking and tracking system, whenever and wherever you are.</p>

          <div class="col-md-12 appstore-dl-container">
            <%= image_tag 'googledl.png', class: 'appstore-img-dl' %>

            <%= image_tag 'appledl.png', class: 'appstore-img-dl' %>
          </div>

        </div>
      </div>
    </div>
  </div>

  <!-- / Section - Partners -->
  <div class="section-row mid">
    <div class="container">
      <div class="row">
        <h2>Featured Partners</h2>
        <p class="headline-description">These Are Some Of Our Top Class Partnering Centres & Studios</p>
        <% if @featured_partners.present? %>

          <% @featured_partners.each_with_index do |partner, index| %>
            <% if index == 0 %>
              <div class="col-md-3">
            <% elsif index == 1 %>
              <div class="col-md-5">
            <% elsif index == 2 %>
              <div class="col-md-4">
            <% elsif index == 3 %>
              <div class="col-md-5">
            <% elsif index == 4 %>
              <div class="col-md-4">
            <% elsif index == 5 %>
              <div class="col-md-3">
            <% end %>
              <div class="partner-feature-img">
                <%= image_tag partner.img_url, class: "partner-bg" %>
                <div class="bg-overlay"></div>
                <div class="company">
                  <%= partner.company %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="col-md-3">
          <div class="cta-partner">
            <div class="title">Get Started</div>
            <div class="description">To View More Partners</div>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="section-row last-cta-container cta-container gray-bg">
    <div class="container">
      <div class="row">

        <div class="col-md-6"></div>
        <div class="col-md-6 col-xs-12 footer-cta-container">

          <%= form_tag contact_request_zipcodes_path, class: 'form-inline send-request-zipcode-form', id: 'bottom-request-zipcode-form' do %>
            <p class="footer-description">
              Sign up is Free & get 2 Free classes worth RM50 from multiple choices. For limited time only. Don’t miss out!
            </p>

            <div class="form-group">
              <div class="user-email">
                <%= email_field_tag :email, nil,  placeholder: "Email", class: 'contact-request-text', required: true %>
              </div>
            </div>

            <div class="form-group">
              <div class="user-postcode">
                <%= text_field_tag :zipcode, nil, placeholder: 'Postcode', class: 'contact-request-text', required: true %>
              </div>
            </div>

            <%= submit_tag "Get Started", class: 'btn btn-primary' %>
          <% end %>

        </div>


      </div>
    </div>
  </div>
  <% end %>

</div>


<!-- Modal -->
<div class="modal fade" id="comingsoon" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body txt-align-center">
      <%= image_tag 'zipcode-no-result.png', height: '100', width: '300' %>
      <br>
      <br>

      <p>Oopss! We’re not in your location yet. We’ll <strong>definitely</strong> notify you once we’ve arrived at your neighborhood very soon! Meanwhile, check out hundreds of best curated activities and classes for kids!</p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Free to Explore', schedules_path, class: 'btn btn-lg btn-primary gp-button' %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/invite.html.haml
- provide(:title, "Request Invite")
/ Request Invite section
%section.margin-two
  = render 'shared/invite'
/ end Request Invite section

app/views/static_pages/partners.html.erb
<% provide(:title, "Sign Up as Partner") %>

<div class="content white-bg no-padding">
  <%= render 'shared/notice', locals: { flash: flash } if flash.present? %>

  <div class="section-row" id='partner-header-div'>
    <div id='partner-overlay'></div>
    <div class="container">
      <div class='partner-header-inner-div'>
        <h1>
          Increase Your Revenue
          <br>With GeniusPass
        </h1>

        <%= link_to 'Get Started Now', '#partnership-signup-div', class: 'btn gp-button' %>
      </div>
    </div>
  </div>

  <div class="section-row" id='partner-lead-div'>
    <div class="container">
      <h2>Expand Your Business By Partnering With GeniusPass</h2>

      <div class="col-md-3 lead-div">
        <%= image_tag 'girl.png' %>

        <h3>User Growth</h3>
        <p>Get discovered and showcase your classes to thousand of users</p>
      </div>

      <div class="col-md-3 lead-div">
        <%= image_tag 'telemarketer.png' %>

        <h3>Partner's Support</h3>
        <p>Best support guaranteed 24 hours a day and 7 days a week</p>
      </div>
      <div class="col-md-3 lead-div">
        <%= image_tag 'megaphone.png' %>

        <h3>Brand Presence</h3>
        <p>Build strong branding and valuable exposure for your centre</p>
      </div>
      <div class="col-md-3 lead-div">
        <%= image_tag 'line-chart.png' %>
        <h3>Increase Revenue</h3>
        <p>Track your revenue, measure performance and improvise</p>
      </div>
    </div>
  </div>
<!--
  <div class="section-row" id='partner-whyus-div'>
    <div class="container">
      <h2>Why Partner With Us?</h2>

      <div class="col-md-6 lead-div">
        <%= image_tag 'get-discovered.png' %>
        <p>Get discovered and showcase your classes to thousand of users</p>
      </div>
      <div class="col-md-6 lead-div">
        <%= image_tag 'strong-branding.png' %>
        <p>Build strong branding and exposure of your centre</p>
      </div>
      <div class="col-md-6 lead-div">
        <%= image_tag 'visible-everytime.png' %>
        <p>Be visible to potential consumers 24 hours a day and 7 days a week</p>
      </div>
      <div class="col-md-6 lead-div">
        <%= image_tag 'track-revenue.png' %>
        <p>Track your revenue, measure performance and improvise</p>
      </div>
    </div>
  </div> -->

  <div class="section-row" id='partnership-signup-div'>
    <div class="container">
      <h2>Our Team Will Get Connected With You As Soon As Possible</h2>
      <p>Kindly fill up the form below</p>
      <%= form_for @partnership, url: partner_signup_path, html: { class: 'form-horizontal', id: 'partnership-sign-up-form' } do |f| %>
        <div class="form-group">
          <%= f.label 'City', class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :city, class: 'form-control', required: true %>
          </div>
        </div>

        <div class="form-group">
        <label class="col-sm-3 control-label" for="partnership_sign_up_Company Name">Company Name</label>
          <div class="col-sm-9">
            <%= f.text_field :company_name, class: 'form-control', required: true %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label" for="partnership_sign_up_Website / Facebook">Website / Facebook</label>
          <div class="col-sm-9">
            <%= f.text_field :website, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label 'Name', class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: 'form-control', required: true %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label 'Email', class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.email_field :email, class: 'form-control', required: true %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label" for="partnership_sign_up_Phone No.">Phone No.</label>
          <div class="col-sm-9">
            <%= f.text_field :phone, class: 'form-control', required: true %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label 'Address', class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_area :address, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label 'Comments', class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-10">
            <%= f.submit 'Get in Touch', class: 'btn btn-lg gp-button' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/static_pages/pricing.html.haml
- provide(:title, "Pricing")
%section
  .container
    .row
      .pricing
        .col-md-4.center-col.sm-margin-bottom-five.sm-no-margin-top
          .pricing-box.no-border
            .pricing-title
              %h1 Pricing
            .pricing-price
              %span.price-unit> RM
              99
              %span.price-tenure /month for 1st child
            .pricing-features
              %ul
                %li
                  %strong Unlimited
                  Classes
                %li Extra child will only cost RM70/mth/child
            .pricing-action
              = link_to 'Request Invite', invite_path, class: "highlight-button-dark btn btn-medium btn-round button"

app/views/static_pages/privacy.html.haml
- provide(:title, "Privacy Policy")
- provide(:page_title_bg, asset_path('background-footer.jpg'))
.content.policy-page.white-bg
  = render partial: 'layouts/page_title', locals: { page_title: 'Privacy Policy' }
  .container
    - if StaticPageContent.find_by_key("PrivacyPolicy").present?
      = StaticPageContent.find_by_key("PrivacyPolicy").value.html_safe

app/views/static_pages/terms.html.haml
- provide(:title, "Terms of Use")
- provide(:page_title_bg, asset_path('background-footer.jpg'))
.content.terms-page.white-bg
  = render partial: 'layouts/page_title', locals: { page_title: 'Terms of Use' }
  .container
    - if StaticPageContent.find_by_key("TermOfUse").present?
      = StaticPageContent.find_by_key("TermOfUse").value.html_safe