config/routes.rb
Rails.application.routes.draw do

  apipie
  namespace :api, defaults: { format: 'json' } do
    resources :children, only: [:create, :index] do
      resources :reservations

      member do
        get     'curated'
        get     'development_elements'
        get     'save_availability'
        patch   'update_availability'
      end

      resources :availability, only: [:create, :update]
    end
    resources :subscriptions, only: [:index]
    resources :schedules, only: [:index, :update]
    resources :users, only: [:update]

    post    'register',           to: 'registrations#create'
    post    'facebook_callback',  to: 'registrations#facebook'
    post    'login',              to: 'sessions#create'
    post    'facebook_callback',  to: 'sessions#facebook'
    post    'forgot_password',    to: 'sessions#forgot'
    delete  'logout',             to: 'sessions#destroy'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :contact_requests
  resources :zipcodes do
    collection do
      post :contact_request
    end
  end

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :static_page_contents
  resources :promo_codes
  get 'cards/new'

  root 'static_pages#index'

  get 'comming_soon', to: 'static_pages#comming_soon', as: 'comming_soon'
  get 'faq',      to: 'static_pages#faq'
  get 'terms',    to: 'static_pages#terms'
  get 'privacy',  to: 'static_pages#privacy'
  get 'become-partner', to: 'static_pages#partners', as: 'partner_signup'
  post 'become-partner', to: 'static_pages#partners'

  post 'charged_successfully', to: 'subscriptions#charged_successfully'

  get 'onboard', to: 'users#onboard', as: 'onboard'

  resources :schedules, only: [:index, :show] do
    patch 'archive',   on: :member
    patch 'unarchive', on: :member

    collection do
      get  'curated'
    end

    resources :reservations, only: [:new, :create, :destroy]
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                                                                          registrations: 'users/registrations',
                                                                                          passwords: 'users/passwords' }

  resources :users, only: [:show] do
    collection do
      get   :select_plan
      get   :new_referal_code
      post  :check_referal_code
    end

    member do
      patch 'add_child'
    end
    post :promo_code
    resources :children, except: [:index, :show]
  end

  resources :children, only: [:show] do
    ## subscriptions ##
    resources :subscriptions, only: [:new, :create, :show, :destroy]

    collection do
      get   'achievements'
    end
    member do
      get  'curated'
    end
  end

  resources :partners do
    collection do
      get :loadmore
    end
    resources :klasses, :schedules, except: [:index, :show]
  end

  # match 'users/:id' => 'users#destroy', via: :delete, as: 'admin_destroy_user'

  resources :cities, path: 'city', except: [:index, :show]
  resources :activities, except: [:index, :show]

  resources :rewards, only: [:index] do
    member do
      get   'claim'
    end
  end

  # Admin's Devise settings
  # devise_for :admins, path: 'admin', path_names: { sign_in: 'login', sign_out: 'logout' }

  ## cards ##
  resources :cards
end

app/models/static_page_content.rb
class StaticPageContent < ActiveRecord::Base
  include Bootsy::Container

end

app/controllers/static_page_contents_controller.rb
class StaticPageContentsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_static_page_content, only: [:show, :edit, :update, :destroy]

  # GET /static_page_contents
  def index
    @static_page_contents = StaticPageContent.all
  end

  # GET /static_page_contents/1
  def show
  end

  # GET /static_page_contents/new
  def new
    @static_page_content = StaticPageContent.new
  end

  # GET /static_page_contents/1/edit
  def edit
  end

  # POST /static_page_contents
  def create
    @static_page_content = StaticPageContent.new(static_page_content_params)

    if @static_page_content.save
      redirect_to @static_page_content, notice: 'Static page content was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /static_page_contents/1
  def update
    if @static_page_content.update(static_page_content_params)
      redirect_to @static_page_content, notice: 'Static page content was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /static_page_contents/1
  def destroy
    @static_page_content.destroy
    redirect_to static_page_contents_url, notice: 'Static page content was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page_content
      @static_page_content = StaticPageContent.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def static_page_content_params
      params.require(:static_page_content).permit(:key, :value, :bootsy_image_gallery_id)
    end
end

app/helpers/static_page_contents_helper.rb
module StaticPageContentsHelper
end

app/views/static_page_contents/_form.html.haml
= simple_form_for(@static_page_content) do |f|
  = f.error_notification

  .form-inputs
    = f.input :key, input_html: {placeholder: 'key'}
    = f.input :value, as: :bootsy, input_html: {rows: 10}

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/static_page_contents/edit.html.haml
%h1 Editing static_page_content

= render 'form'

= link_to 'Show', @static_page_content
\|
= link_to 'Back', static_page_contents_path

app/views/static_page_contents/index.html.haml
- provide(:title, "Staic page management")
- provide(:page_title_bg, asset_path('background-footer.jpg'))
.container.content.faq-page.white-bg
  = render partial: 'layouts/page_title', locals: { page_title: 'Static Page Management' }
  %h1 Admin Static Pages

  %table.table.table-striped.table-bordered
    %thead
      %tr
        %th Key
        %th
        %th
        %th

    %tbody
      - @static_page_contents.each do |static_page_content|
        %tr
          %td= static_page_content.key
          %td= link_to 'Show', static_page_content
          %td= link_to 'Edit', edit_static_page_content_path(static_page_content)
          %td= link_to 'Destroy', static_page_content, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br
  = link_to 'New Static page content', new_static_page_content_path, class: 'btn btn-primary'

app/views/static_page_contents/new.html.haml
.container
  %h1 New Admin static page

  = render 'form'

  = link_to 'Back', static_page_contents_path

app/views/static_page_contents/show.html.haml
.container.content.faq-page.white-bg
  = render partial: 'layouts/page_title', locals: { page_title: @static_page_content.key }
  = @static_page_content.value.html_safe
%br/
= link_to 'Back', static_page_contents_path