config/routes.rb
Rails.application.routes.draw do

  apipie
  namespace :api, defaults: { format: 'json' } do
    resources :children, only: [:create, :index] do
      resources :reservations

      member do
        get     'curated'
        get     'development_elements'
        get     'save_availability'
        patch   'update_availability'
      end

      resources :availability, only: [:create, :update]
    end
    resources :subscriptions, only: [:index]
    resources :schedules, only: [:index, :update]
    resources :users, only: [:update]

    post    'register',           to: 'registrations#create'
    post    'facebook_callback',  to: 'registrations#facebook'
    post    'login',              to: 'sessions#create'
    post    'facebook_callback',  to: 'sessions#facebook'
    post    'forgot_password',    to: 'sessions#forgot'
    delete  'logout',             to: 'sessions#destroy'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :contact_requests
  resources :zipcodes do
    collection do
      post :contact_request
    end
  end

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :static_page_contents
  resources :promo_codes
  get 'cards/new'

  root 'static_pages#index'

  get 'comming_soon', to: 'static_pages#comming_soon', as: 'comming_soon'
  get 'faq',      to: 'static_pages#faq'
  get 'terms',    to: 'static_pages#terms'
  get 'privacy',  to: 'static_pages#privacy'
  get 'become-partner', to: 'static_pages#partners', as: 'partner_signup'
  post 'become-partner', to: 'static_pages#partners'

  post 'charged_successfully', to: 'subscriptions#charged_successfully'

  get 'onboard', to: 'users#onboard', as: 'onboard'

  resources :schedules, only: [:index, :show] do
    patch 'archive',   on: :member
    patch 'unarchive', on: :member

    collection do
      get  'curated'
    end

    resources :reservations, only: [:new, :create, :destroy]
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                                                                          registrations: 'users/registrations',
                                                                                          passwords: 'users/passwords' }

  resources :users, only: [:show] do
    collection do
      get   :select_plan
      get   :new_referal_code
      post  :check_referal_code
    end

    member do
      patch 'add_child'
    end
    post :promo_code
    resources :children, except: [:index, :show]
  end

  resources :children, only: [:show] do
    ## subscriptions ##
    resources :subscriptions, only: [:new, :create, :show, :destroy]

    collection do
      get   'achievements'
    end
    member do
      get  'curated'
    end
  end

  resources :partners do
    collection do
      get :loadmore
    end
    resources :klasses, :schedules, except: [:index, :show]
  end

  # match 'users/:id' => 'users#destroy', via: :delete, as: 'admin_destroy_user'

  resources :cities, path: 'city', except: [:index, :show]
  resources :activities, except: [:index, :show]

  resources :rewards, only: [:index] do
    member do
      get   'claim'
    end
  end

  # Admin's Devise settings
  # devise_for :admins, path: 'admin', path_names: { sign_in: 'login', sign_out: 'logout' }

  ## cards ##
  resources :cards
end

app/views/shared/_children_list.html.haml
.sidebar-widget
  %h3 Children
  .children-list
    %table.table.children-list-table
      - @children = current_user.children.sort_by_age_name
      - @children.each do |child|
        %tr
          %td.children-name
            = child.fullname
          %td.children-number= age(child)
          /%td.children-edit
          /  = link_to " ", edit_user_child_path(current_user, child), :class => "fa fa-pencil"
    .sidebar-footer
      = link_to "+ Add", new_user_child_path(current_user), class: "gp-button"

app/views/shared/_devise_messages.html.haml
- if devise_controller?
  - if notice
    .alert-style7.alert-success
      = notice
    .alert-style6
  - if alert
    .alert-danger.alert-style7
      = alert

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .alert-style7.alert-danger{:role => "alert"}
    - object.errors.full_messages.each do |message|
      %span= message.html_safe

app/views/shared/_inline_error.html.erb
<div class="alert-style6">
  <div class="alert alert-danger no-padding-left-right" role="alert">
    <i class="icon-sad"></i>
    <span>
      <%= flash[:error] %>
    </span>
  </div>
</div>

app/views/shared/_invite.html.haml
.container
  / Title
  .row
    .col-md-7.col-sm-10.center-col.text-center.margin-two-four
      %h2.no-margin-top Request an Invite
      .separator-line.bg-yellow.margin-three
      %p.letter-spacing-1.no-margin-bottom Early adopters will be rewarded with discount coupons!
      %small.no-margin Promotion open for the first 100 children in each city.
  / End Title
  / Begin MailChimp Signup Form
  .row
    #mc_embed_signup.col-md-6.col-md-offset-3
      %form#mc-embedded-subscribe-form.validate{:action => "//geniuspass.us10.list-manage.com/subscribe/post?u=06b2675db3a573a09ca434ca3&id=2b51fe0248", :method => "post", :name => "mc-embedded-subscribe-form", :novalidate => "", :target => "_blank"}
        #mc_embed_signup_scroll
          .mc-field-group.field
            %label.letter-spacing-1{:for => "mce-EMAIL"}
              Email Address
              %span.asterisk *
            %input#mce-EMAIL.required.email{:name => "EMAIL", :type => "email", :value => ""}/
          .mc-field-group.field
            %label.letter-spacing-1{:for => "mce-CITY"}
              Your City
              %span.asterisk *
            %select#mce-CITY.required{:name => "CITY"}
              %option{:value => ""}
              %option{:value => "Klang"} Klang
              %option{:value => "Kuala Lumpur"} Kuala Lumpur
              %option{:value => "Petaling Jaya"} Petaling Jaya
              %option{:value => "Puchong"} Puchong
              %option{:value => "Putrajaya"} Putrajaya
              %option{:value => "Shah Alam"} Shah Alam
              %option{:value => "Subang Jaya"} Subang Jaya
          #mce-responses.clear
            #mce-error-response.response{:style => "display:none"}
            #mce-success-response.response{:style => "display:none"}
          / real people should not fill this in and expect good things - do not remove this or risk form bot signups
          %div{:style => "position: absolute; left: -5000px;"}
            %input{:name => "b_06b2675db3a573a09ca434ca3_2b51fe0248", :tabindex => "-1", :type => "text", :value => ""}/
          / end hidden input
          .clear.margin-five
            %input#mc-embedded-subscribe.highlight-button-dark.btn.btn-small.btn-round.button{:name => "subscribe", :type => "submit", :value => "Submit"}/
  / End MailChimp Signup Form

app/views/shared/_map.html.haml
%script{:src => "//maps.google.com/maps/api/js?key=AIzaSyCtQZPEck0ngl3-i3mBKA81znMeIpc-HZA"}
%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/js-marker-clusterer/1.0.0/markerclusterer_compiled.js"}
%script{:src => "https://cdn.rawgit.com/googlemaps/v3-utility-library/master/infobox/src/infobox_packed.js", :type => "text/javascript"}


:javascript

  handler = Gmaps.build('Google');
  handler.buildMap(
    { provider:
      {
        scrollwheel: false,
        draggable: false,
        mapTypeControl: false,
        panControl: false,
        scaleControl: false,
        streetViewControl: false,
        zoomControlOptions: {
            style: google.maps.ZoomControlStyle.SMALL,
            position: google.maps.ControlPosition.LEFT_TOP
        },
      }, internal: {id: 'map'}}, function()
  {
    var markers = handler.addMarkers(#{markers.to_json});
    handler.bounds.extendWith(markers);
    handler.map.centerOn(markers[0]);

    if ( #{markers.length} == 1)
    {
      handler.getMap().setZoom(14);
    }
    else
    {
      handler.getMap().setZoom(12);
    }
    //handler.fitMapToBounds();
  });

app/views/shared/_notice.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/shared/_schedule.html.erb
<div class="schedule-item-container">
  <div class="schedule-image">
    <%= image_tag @schedule.partner.img_url, alt: "photo of #{@schedule.partner.company}" %>
  </div>
  <div class="schedule-details">
    <div class="level">
      <%= @schedule.klass.level %>
    </div>
    <h3 class="activity">
      <%= @schedule.klass.name %>
    </h3>
    <div class="partner">
      by <%= link_to @schedule.partner.company, partner_path(@schedule.partner) %>
    </div>
    <div class="description">
      <%= @schedule.klass.description %>
    </div>
    <dl class="dl-horizontal">
      <hr/>
      <dt>Date:</dt>
      <dd>
        <%= @schedule.starts_at.strftime("%-d %b %Y") %>
      </dd>
      <hr/>
      <dt>Time:</dt>
      <dd>
        <%= @schedule.starts_at.strftime("%l:%M%P") %>
        - <%= @schedule.ends_at.strftime("%l:%M%P") %>
      </dd>
      <hr/>
      <dt>Age:</dt>
      <dd>
        <%= @schedule.klass.age_start %>
        - <%= @schedule.klass.age_end %>
      </dd>
      <hr/>
      <dt>Elements:</dt>
      <dd>
        <% if @schedule.klass.development_elements.present? %>
          <% @schedule.klass.klass_elements.each do |element| %>
            <div class="col-md-4 col-xs-4 reward-popout-div">
              <div class='development-elements'>
                <div class='element-img'>
                  <%= image_tag "#{element.development_element.title.downcase}.png" %>
                </div>
                <div class='element-title'>
                  <strong><%= element.development_element.title %></strong>
                  <br>(<%= element.points %> Points)
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </dd>
      <hr/>
    </dl>
    <div class="address">
      <h3>Address</h3>
      <p>
        <i class="fa fa-map-marker"></i>
        <%= @schedule.partner.address %>
        , <%= @schedule.city.name %>, <%= @schedule.partner.state %>
      </p>
    </div>
  </div>
</div>

app/views/shared/_tawkto.html.erb
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var $_Tawk_API={},$_Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/578751c3752d939c0f7e2927/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->