config/routes.rb
Rails.application.routes.draw do

  apipie
  namespace :api, defaults: { format: 'json' } do
    resources :children, only: [:create, :index] do
      resources :reservations

      member do
        get     'curated'
        get     'development_elements'
        get     'save_availability'
        patch   'update_availability'
      end

      resources :availability, only: [:create, :update]
    end
    resources :subscriptions, only: [:index]
    resources :schedules, only: [:index, :update]
    resources :users, only: [:update]

    post    'register',           to: 'registrations#create'
    post    'facebook_callback',  to: 'registrations#facebook'
    post    'login',              to: 'sessions#create'
    post    'facebook_callback',  to: 'sessions#facebook'
    post    'forgot_password',    to: 'sessions#forgot'
    delete  'logout',             to: 'sessions#destroy'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :contact_requests
  resources :zipcodes do
    collection do
      post :contact_request
    end
  end

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :static_page_contents
  resources :promo_codes
  get 'cards/new'

  root 'static_pages#index'

  get 'comming_soon', to: 'static_pages#comming_soon', as: 'comming_soon'
  get 'faq',      to: 'static_pages#faq'
  get 'terms',    to: 'static_pages#terms'
  get 'privacy',  to: 'static_pages#privacy'
  get 'become-partner', to: 'static_pages#partners', as: 'partner_signup'
  post 'become-partner', to: 'static_pages#partners'

  post 'charged_successfully', to: 'subscriptions#charged_successfully'

  get 'onboard', to: 'users#onboard', as: 'onboard'

  resources :schedules, only: [:index, :show] do
    patch 'archive',   on: :member
    patch 'unarchive', on: :member

    collection do
      get  'curated'
    end

    resources :reservations, only: [:new, :create, :destroy]
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                                                                          registrations: 'users/registrations',
                                                                                          passwords: 'users/passwords' }

  resources :users, only: [:show] do
    collection do
      get   :select_plan
      get   :new_referal_code
      post  :check_referal_code
    end

    member do
      patch 'add_child'
    end
    post :promo_code
    resources :children, except: [:index, :show]
  end

  resources :children, only: [:show] do
    ## subscriptions ##
    resources :subscriptions, only: [:new, :create, :show, :destroy]

    collection do
      get   'achievements'
    end
    member do
      get  'curated'
    end
  end

  resources :partners do
    collection do
      get :loadmore
    end
    resources :klasses, :schedules, except: [:index, :show]
  end

  # match 'users/:id' => 'users#destroy', via: :delete, as: 'admin_destroy_user'

  resources :cities, path: 'city', except: [:index, :show]
  resources :activities, except: [:index, :show]

  resources :rewards, only: [:index] do
    member do
      get   'claim'
    end
  end

  # Admin's Devise settings
  # devise_for :admins, path: 'admin', path_names: { sign_in: 'login', sign_out: 'logout' }

  ## cards ##
  resources :cards
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  ## Associations ##
  belongs_to :user
  belongs_to :child
  belongs_to :subscription_type

  ## Validations ##
  validates :child_id, :subscription_type_id, presence: true
  validate  :valid_promo_code

  after_create :send_subscription_notification

  scope :active, -> { where(status: true) }

  ## Instance Methods ##
  def sync_subscription(nounce)
    result = Braintree::PaymentMethod.create(
      :customer_id => user.customer_id,
      :payment_method_nonce => nounce
    )
    plan_id = "RM#{subscription_type.price}"
    discount_id = "RM20"
    if result.success?
      token = result.payment_method.token
      result = Braintree::Subscription.create(
                            :payment_method_token => token,
                            :plan_id => plan_id,
                            :discounts =>
                                      {
                                        :add => [ :inherited_from_id => discount_id,
                                                  :quantity          => discounts_quantity
                                                ]
                                      })

      if result.success?
        referred_by.referals.build(:referred_to_id => user.id).save     if promo_code.present? && referred_by.present?
        self.subscription_id = result.subscription.id
        self.start_date = DateTime.now
        self.save!
      else
        false
      end
    else
      false
    end
  end

  def expired?
    Time.now > renewal_date
  end

  def free_package?
    subscription_type == SubscriptionType.free
  end

  def discounts_quantity
    quantity = 0
    quantity = quantity + 1 if promo_code.present?
    quantity = quantity + 1 if user.can_avail_discounted_plans?
    if user.can_have_referal_discounts?
      if (subscription_type.price.to_i - quantity*20) > 20
        user.available_referals.first.update_attributes( :rewards_used => true)
        quantity = quantity + 1
      end
    end
    return quantity
  end

  def subscriped_on
    created_at.strftime('%d,%B-%y at %H:%M %p')
  end

  def plan
    p = Plan.new
    plan = p.get_plan(plan_id)
  end

  def renewal_date
    created_at + 30.days if created_at
  end

  def print_status
    status ? 'Active' : 'De-Active'
  end

  def unsubscribe
    unless subscription_type == SubscriptionType.free
      result = Braintree::Subscription.cancel(subscription_id)
    end
    self.update_attributes(status: false, cancelled_on: DateTime.now)
  end

  def referred_by
    User.find_by_promo_code( promo_code)
  end

  def send_subscription_notification
    SubscriptionMailer.invite(self.user).deliver_now
  end

  private

  def valid_promo_code
    if promo_code.present?
      unless referred_by.present? || PromoCode.find_by_code( promo_code)
        errors.add( :promo_code, "Invalid promo code")
      else
        if user.subscriptions.where.not( :id => self.id).where(:promo_code => promo_code ).present?
          errors.add( :promo_code, "You can not use your own promo code")
        end
      end
    end
  end

end

app/models/subscription_type.rb
class SubscriptionType < ActiveRecord::Base

  has_many :subscriptions

  scope :paid, -> { where.not(name: 'Free') }
  scope :asc, -> { order('price asc') }
  scope :first_child_paid_packages, -> { where.not(name: 'Free') }
  scope :onward_child_paid_packages, -> { where.not(name: 'Free').where(two_child_onward_package: true) }

  def free?
    price.to_i == 0
  end

  def pro?
    self == SubscriptionType.pro
  end

  def self.free
    find_by_name('Free')
  end

  def self.pro
    find_by_name('Pro')
  end

  def self.amateur
    find_by_name('Amateur')
  end

end

app/controllers/api/subscriptions_controller.rb
class Api::SubscriptionsController < Api::BaseController

  api :GET, '/subscriptions', 'Get a list of subscription packages'
  param :api_token, String, desc: "This API token will be needed to get authorized."
  formats ['json']
  error code: 403, desc: "Unauthorized"
  def index
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:charged_successfully]
  before_action :set_child, except: [:charged_successfully]
  def new
    paid_subscription_ids = SubscriptionType.paid.pluck(:id)

    if current_user.subscriptions.where(subscription_type_id: paid_subscription_ids).active.size >= 1
      @packages = SubscriptionType.onward_child_paid_packages.asc
    else
      @packages = SubscriptionType.paid.asc
    end
    @client_token = Braintree::ClientToken.generate(customer_id: current_user.customer_id)
    if @child.subscription.present?
      @subscription = @child.subscription
    else
      @subscription = @child.build_subscription
    end
    @user = current_user
  end

  def create
    @user = current_user
    @subscription = @child.build_subscription(subscription_params)
    @subscription.user = @user
    if @subscription.save
      unless @subscription.subscription_type == SubscriptionType.free
        if @subscription.sync_subscription(params[:payment_method_nonce])
          redirect_to schedules_path, notice: "You have subscribed successfully"
        else
          @subscription.destroy
          redirect_to child_path(@child), notice: "Please try again"
        end
      else
        redirect_to schedules_path, notice: "You free subscription added successfully."
      end
    else
      render :new
    end
  end

  def show
    @subscription = @child.subscription
    @plan = @subscription.plan
  end

  def destroy
    @subscription = @child.subscription
    @subscription.unsubscribe
    redirect_to schedules_path, notice: "You have unsubscribed successfully"
  end

  def charged_successfully
    webhook_notification = Braintree::WebhookNotification.parse(params["bt_signature"],params["bt_payload"])
    if webhook_notification.subscription.present?
      subscription = Subscription.find_by(subscription_id: webhook_notification.subscription.id)
      subscription.update_attributes(renewal_date: DateTime.now + 30.days, start_date: DateTime.now)
    end
    render nothing: true, status: 200
  end

  private
  def set_child
    @child = current_user.children.find(params[:child_id])
  end

  def subscription_params
    params.require(:subscription).permit( :promo_code, :subscription_type_id)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/new.html.erb
<% provide(:title, "Payment") %>
<% provide(:nav_color, "link-white") %>
<% provide(:page_title_bg, asset_path('background-footer.jpg')) %>

<div class='content subscribe-page'>
  <%= render partial: 'layouts/page_title', locals: { page_title: 'Payment' } %>
  <%= render 'shared/notice', locals: { flash: flash } if flash.present? %>



  <div class="container">
    <div class="content-main">
      <h3>Select Your Plan</h3>
      <div class="package-pricing-table-container">

        <% @packages.each do |plan| %>
          <div class="package-pricing-table <%= "featured" if plan.featured? %>">
            <div class="package-pricing-title">
              <%= plan.name %>
            </div>

            <div class="package-pricing-price">
              <% if plan.on_discount? %>
                <span class="package-original-pricing-number">
                  RM<%= plan.price %>
                </span>

                <span class="package-pricing-currency">RM</span>
                <span class="package-pricing-number">
                  <%= plan.discount_price %>
                </span>
                <span class="package-pricing-subtitle">
                  Per Month
                  <span class="package-pricing-saving-subtitle">
                    (Save RM<%= plan.price - plan.discount_price %>)
                  </span>
                </span>
              <% else %>
                <span class="package-pricing-currency">RM</span>
                <span class="package-pricing-number">
                  <%= plan.price %>
                </span>
                <span class="package-pricing-subtitle">Per Month</span>
              <% end %>
              <span class="package-pricing-details">
                <%= "#{plan.activities_allowed} Activities Per Month" %>
              </span>
            </div>

            <div class="package-pricing-content">
              <p>We make it really simple for you:</p>
              <ul>
                <li>
                  <i class="fa fa-check"></i>
                  Auto Renewal
                </li>
                <li>
                  <i class="fa fa-check"></i>
                  No Contract
                </li>
                <li>
                  <i class="fa fa-check"></i>
                  No Termination Fee
                </li>
                <li>
                  <i class="fa fa-check"></i>
                  Cancel Anytime
                </li>
              </ul>
            </div>

            <div class="package-pricing-action">
              <div class="gp-link" data-toggle="collapse" href="#package-promocode-<%= plan.name %>" title="Got Promo Code?">
                Got Promo Code?
              </div>

              <div class="package-promo-code collapse" id="package-promocode-<%= plan.name %>">
                <div class="promo_code_plan">
                  <%= render :partial => "users/referal_code_form" %>
                </div>
              </div>

              <button class="gp-button open-modal" data-id="RM79" data-promocode="" data-subscription-type-id="3" data-target="#package-subscription" data-toggle="modal" href="#" title="Select Plan">
                <% if @child.subscription.present? and !@child.subscription.new_record? %>
                  Upgrade Plan
                <% else %>
                  Select Plan
                <% end %>
              </button>
            </div>
          </div>
        <% end %>

      </div>

      <% if @child.subscription.present? and !@child.subscription.new_record? %>
        <% if @child.subscription.free_package? %>
          <!-- Cannot downgrade -->
        <% else %>
          <% if !@child.subscription.new_record? %>
            <p class="basic-package-link">
              <%= link_to 'Unsubscribe Package', child_subscription_path(@child, @child.subscription), method: :delete, data: { confirm: 'Are you sure you want to unsubscribe this package?' }, class: "gp-link" %>
            </p>
          <% end %>
        <% end %>
      <% else %>
        <div class="basic-package-link">
          <% plan = SubscriptionType.free %>
          <div class='col-md-7'>
            <span class='free-activities-months'>
              Get Started With <%= plan.activities_allowed %> Free <%= pluralize(plan.activities_allowed, 'Activity') %>
            </span>
          </div>

          <div class='col-md-5'>
            <%= link_to "Select Plan", child_subscriptions_path(@child, subscription: { :subscription_type_id => plan.id }), method: :post, class: "free-package-btn" %>
            <div class='free-valid'>*valid for 30 days</div>
          </div>
          <div class='clearfix'></div>
        </div>
        <div class='clearfix'></div>
      <% end %>

    </div>
  </div>

  <div class="modal fade" id="package-subscription" role="dialog" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button aria-label="Close" class="close" data-dismiss="modal" type="button">
            <span aria-hidden="true"></span> x
          </button>
          <h4 class="modal-title">Subscribe Your Plan</h4>
        </div>
        <%= form_for @subscription, url: child_subscriptions_path(@child) do |f| %>
          <div class="modal-body">
            <div class="field">
              <%= f.hidden_field :plan_id %>
              <%= f.hidden_field :promo_code %>
              <%= f.hidden_field :subscription_type_id %>
              <div id="dropin"></div>
            </div>
          </div>
          <div class="modal-footer">
            <%= image_tag 'ssl-img.png', width: '150px', height: '80px', class: 'pull-left' %>
            <%= f.submit "Confirm Payment", class: "btn btn-danger", :id => "suscribe_btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>

  $(document).ready(function(){
    $(".open-modal").click(function() {
      var promo_code = $(this).data('promocode');
      var subscription_type_id = $(this).data('subscription-type-id')
      var planId = $(this).data('id');
      $("#subscription_plan_id").val( planId );
      $("#subscription_promo_code").val( promo_code);
      $("#subscription_subscription_type_id").val( subscription_type_id);
    });
  });

</script>

<%= content_for :javascript do %>
  <%= javascript_include_tag "https://js.braintreegateway.com/v2/braintree.js" %>
  <script>

     var client_token = "<%= @client_token %>";
     braintree.setup(
       client_token,
       'dropin', {
         container: 'dropin',
         onReady: function(){ $("#suscribe_btn").prop('disabled', false); }
       });

  </script>
<% end %>

app/views/subscriptions/show.html.haml
- provide(:title, "Dashboard")
- provide(:nav_color, "link-white")
= render partial: 'layouts/page_title', locals: { page_title: 'Dashboard' }
= render 'shared/notice', locals: { flash: flash } if flash.present?
%section.padding-two
  .container
    .row
      .col-md-9.col-md-offset-1
        %table.table
          %tr
            %th Plan Name
            %th Subscriped On
            %th Amount
            %th Summary
            %th Plan Duration
            %th Status
          %tr
            %td
              %label.label.label-primary= @subscription.plan_id
            %td
              %label.label.label-default= @subscription.subscriped_on
            %td= "#{@plan.currency_iso_code} #{@plan.price.to_f}"
            %td= @plan.description
            %td= @plan.billing_frequency.to_s + " month"
            %td
              %label.label.label-success= @subscription.print_status